name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: xTendLoRa/LWmesh@cppcheckWorkFlow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
