name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: xTendLoRa/LWmesh@master
        with:
          github_token: 0447b4479d5f9f14fdef0bd07ada655e543af883
          check_library: enable
          skip_preprocessor: enable
          enable: all
          inconclusive: enable
          inline_suppression: enable
          force_language: c
          max_ctu_depth: 2
          platform: native
          output_file: ./cppcheck_report.txt
